CREATE TABLE TokenStates (
    Id INT AUTO_INCREMENT NOT NULL,
    Token NVARCHAR(500) NOT NULL,
    UserId NVARCHAR(128) NOT NULL,
    RefreshTokenExpires DATETIME NOT NULL,
    TimeCreated DATETIME NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Device NVARCHAR(100) NOT NULL,
    PRIMARY KEY (Id)
);